export const PERMISSIONS = {
  VIEW_PROFILE: "VIEW_PROFILE",
  EDIT_PROFILE: "EDIT_PROFILE",

  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  VERIFY_CERTIFICATE: "VERIFY_CERTIFICATE",

  APPLY_JOB: "APPLY_JOB",
  POST_JOB: "POST_JOB",

  CREATE_EVENT: "CREATE_EVENT",

  SEND_MESSAGE: "SEND_MESSAGE",

  MANAGE_COLLEGE: "MANAGE_COLLEGE",
  MANAGE_UNIVERSITY: "MANAGE_UNIVERSITY",
};