import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.APPLY_JOB,
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.SEND_MESSAGE,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VERIFY_CERTIFICATE,
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.SEND_MESSAGE,
  ],

  [ROLES.RECRUITER]: [
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.POST_JOB,
    PERMISSIONS.VERIFY_CERTIFICATE,
    PERMISSIONS.SEND_MESSAGE,
  ],

  [ROLES.ORGANIZATION]: [
    PERMISSIONS.VERIFY_CERTIFICATE,
    PERMISSIONS.CREATE_EVENT,
  ],

  [ROLES.ALUMNI]: [
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.SEND_MESSAGE,
  ],

  [ROLES.COLLEGE_ADMIN]: [
    PERMISSIONS.MANAGE_COLLEGE,
    PERMISSIONS.VERIFY_CERTIFICATE,
  ],

  [ROLES.UNIVERSITY_ADMIN]: [
    PERMISSIONS.MANAGE_UNIVERSITY,
    PERMISSIONS.MANAGE_COLLEGE,
  ],
};